package com.example.coursework2

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper



class MyHelper(context : Context) : SQLiteOpenHelper(context,"MEAL_TABLE",null,1) {
    override fun onCreate(db: SQLiteDatabase?) {
        // Create the MEAL_TABLE table
        db?.execSQL("CREATE TABLE MEAL_TABLE(_id integer primary key autoincrement, MEAL TEXT, DRINK_ALTERNATE TEXT, CATEGORY TEXT, AREA TEXT, INSTRUCTIONS TEXT, MEAL_THUMB TEXT, TAGS TEXT, YOUTUBE TEXT, INGREDIENT1 TEXT, INGREDIENT2 TEXT,INGREDIENT3 TEXT,INGREDIENT4 TEXT,INGREDIENT5 TEXT,INGREDIENT6 TEXT, INGREDIENT7 TEXT, INGREDIENT8 TEXT, INGREDIENT9 TEXT, INGREDIENT10 TEXT, MEASURE1 TEXT, MEASURE2 TEXT, MEASURE3 TEXT, MEASURE4 TEXT, MEASURE5 TEXT, MEASURE6 TEXT, MEASURE7 TEXT, MEASURE8 TEXT, MEASURE9 TEXT, MEASURE10 TEXT,SOURCE TEXT,IMAGE_SOURCE TEXT,CREATIVE_COMMONS_CONFIRMED TEXT,DATE_MODIFIED TEXT)")
        // Insert a new row into the MEAL_TABLE table
        db?.execSQL("INSERT INTO MEAL_TABLE(MEAL,DRINK_ALTERNATE,CATEGORY,AREA,INSTRUCTIONS,MEAL_THUMB,TAGS,YOUTUBE,INGREDIENT1,INGREDIENT2,INGREDIENT3,INGREDIENT4,INGREDIENT5,INGREDIENT6,INGREDIENT7,INGREDIENT8,INGREDIENT9,INGREDIENT10,MEASURE1,MEASURE2,MEASURE3,MEASURE4,MEASURE5,MEASURE6,MEASURE7,MEASURE8,MEASURE9,MEASURE10,SOURCE,IMAGE_SOURCE,CREATIVE_COMMONS_CONFIRMED,DATE_MODIFIED) VALUES('Sweet and Sour Pork', 'NULL','Pork','Chinese','Preparation\\r\\n1. Crack the egg into a bowl. Separate the egg white and yolk.\\r\\n\\r\\nSweet and Sour Pork\\r\\n2. Slice the pork tenderloin into ips.\\r\\n\\r\\n3. Prepare the marinade using a pinch of salt, one teaspoon of starch, two teaspoons of light soy sauce, and an egg white.\\r\\n\\r\\n4. Marinade the pork ips for about 20 minutes.\\r\\n\\r\\n5. Put the remaining starch in a bowl. Add some water and vinegar to make a starchy sauce.\\r\\n\\r\\nSweet and Sour Pork\\r\\nCooking Inuctions\\r\\n1. Pour the cooking oil into a wok and heat to 190\\u00b0C (375\\u00b0F). Add the marinated pork ips and fry them until they turn brown. Remove the cooked pork from the wok and place on a plate.\\r\\n\\r\\n2. Leave some oil in the wok. Put the tomato sauce and white sugar into the wok, and heat until the oil and sauce are fully combined.\\r\\n\\r\\n3. Add some water to the wok and thoroughly heat the sweet and sour sauce before adding the pork ips to it.\\r\\n\\r\\n4. Pour in the starchy sauce. Stir-fry all the ingredients until the pork and sauce are thoroughly mixed together.\\r\\n\\r\\n5. Serve on a plate and add some coriander for decoration','https:\\/\\/www.themealdb.com\\/images\\/media\\/meals\\/1529442316.jpg','Sweet','https:\\/\\/www.youtube.com\\/watch?v=mdaBIhgEAMo','pork','egg','water','salt','sugar','soy sauce','starch','tomato puree','vinegar','coriander','200g','1','dash','1/2 tsp','1 tsp','10g','10g','30g','10g','dash','null','https://www.themealdb.com/images/media/meals/1529442316.jpg','null','null')")
        db?.execSQL("INSERT INTO MEAL_TABLE(MEAL,DRINK_ALTERNATE,CATEGORY,AREA,INSTRUCTIONS,MEAL_THUMB,TAGS,YOUTUBE,INGREDIENT1,INGREDIENT2,INGREDIENT3,INGREDIENT4,INGREDIENT5,INGREDIENT6,INGREDIENT7,INGREDIENT8,INGREDIENT9,INGREDIENT10,MEASURE1,MEASURE2,MEASURE3,MEASURE4,MEASURE5,MEASURE6,MEASURE7,MEASURE8,MEASURE9,MEASURE10,SOURCE,IMAGE_SOURCE,CREATIVE_COMMONS_CONFIRMED,DATE_MODIFIED) VALUES('Chicken Marengo','null','Chicken','French','Heat the oil in a large flameproof casserole dish and stir-fry the mushrooms until they start to soften. Add the chicken legs and cook briefly on each side to colour them a little.\\r\\nPour in the passata, crumble in the stock cube and stir in the olives. Season with black pepper \\u2013 you shouldn\\u2019t need salt. Cover and simmer for 40 mins until the chicken is tender. Sprinkle with parsley and serve with pasta and a salad, or mash and green veg, if you like.','https:\\/\\/www.themealdb.com\\/images\\/media\\/meals\\/qpxvuq1511798906.jpg','null','https:\\/\\/www.youtube.com\\/watch?v=U33HYUr-0Fw','Olive Oil','Mushrooms','Chicken Legs','Passata','Chicken Stock Cube','Black Olives','Parsley','null','null','null','1 tbs','300g','4','500g','1','100g','chopped','null','null','null','https:\\/\\/www.bbcgoodfood.com\\/recipes\\/3146682\\/chicken-marengo','https://www.themealdb.com/images/media/meals/qpxvuq1511798906.jpg','null','null')")
        db?.execSQL("INSERT INTO MEAL_TABLE(MEAL,DRINK_ALTERNATE,CATEGORY,AREA,INSTRUCTIONS,MEAL_THUMB,TAGS,YOUTUBE,INGREDIENT1,INGREDIENT2,INGREDIENT3,INGREDIENT4,INGREDIENT5,INGREDIENT6,INGREDIENT7,INGREDIENT8,INGREDIENT9,INGREDIENT10,MEASURE1,MEASURE2,MEASURE3,MEASURE4,MEASURE5,MEASURE6,MEASURE7,MEASURE8,MEASURE9,MEASURE10,SOURCE,IMAGE_SOURCE,CREATIVE_COMMONS_CONFIRMED,DATE_MODIFIED) VALUES('Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber','null','beef','Vietnamese','Add ingredients: mayonnaise, siracha\\r\\n\\r\\n1\\r\\n\\r\\nPlace rice in a fine-mesh sieve and rinse until water runs clear. Add to a small pot with 1 cup water (2 cups for 4 servings)and a pinch of salt. Bring to a boil, then cover and reduce heat to low. Cook until rice is tender, 15 minutes. Keep covered off heat for at least 10 minutes or until ready to serve.Meanwhile, wash and dry all produce. Peel and finely chop garlic. Zest and quarter lime (for 4 servings, zest 1 lime and quarter both). Trim and halve cucumber lengthwise; thinly slice crosswise into half-moons. Halve, peel, and medium dice onion. Trim, peel, and grate carrot.\\r\\n\\r\\n3\\r\\n\\r\\nIn a medium bowl, combine cucumber, juice from half the lime, \\u00bc tsp sugar(\\u00bd tsp for 4 servings), and a pinch of salt. In a small bowl, combine mayonnaise, a pinch of garlic, a squeeze of lime juice, and as much sriracha as you\\u2019d like. Season with salt and pepper.\\r\\n\\r\\n4\\r\\n\\r\\nHeat a drizzle of oil in a large pan over medium-high heat. Add onion and cook, stirring, until softened, 4-5 minutes. Add beef, remaining garlic, and 2 tsp sugar (4 tsp for 4 servings). Cook, breaking up meat into pieces, until beef is browned and cooked through, 4-5 minutes. Stir in soy sauce. Turn off heat; taste and season with salt and pepper.\\r\\n\\r\\n5\\r\\n\\r\\nFluff rice with a fork; stir in lime zest and 1 TBSP butter. Divide rice between bowls. Arrange beef, grated carrot, and pickled cucumber on top. Top with a squeeze of lime juice. Drizzle with sriracha mayo.','https:\\/\\/www.themealdb.com\\/images\\/media\\/meals\\/z0ageb1583189517.jpg','null','null','rice','Onion','lime','garlic clove','cucumber','carrots','ground beef','soy sauce','null','null','white','1','1','3','1','3 oz','1 lb','2 oz','null','null','null','null','null','null')")
        db?.execSQL("INSERT INTO MEAL_TABLE(MEAL,DRINK_ALTERNATE,CATEGORY,AREA,INSTRUCTIONS,MEAL_THUMB,TAGS,YOUTUBE,INGREDIENT1,INGREDIENT2,INGREDIENT3,INGREDIENT4,INGREDIENT5,INGREDIENT6,INGREDIENT7,INGREDIENT8,INGREDIENT9,INGREDIENT10,MEASURE1,MEASURE2,MEASURE3,MEASURE4,MEASURE5,MEASURE6,MEASURE7,MEASURE8,MEASURE9,MEASURE10,SOURCE,IMAGE_SOURCE,CREATIVE_COMMONS_CONFIRMED,DATE_MODIFIED) VALUES('Leblebi Soup','null','Vegetarian','Tunisian','Heat the oil in a large pot. Add the onion and cook until translucent.\\r\\nDrain the soaked chickpeas and add them to the pot together with the vegetable stock. Bring to the boil, then reduce the heat and cover. Simmer for 30 minutes.\\r\\nIn the meantime toast the cumin in a small ungreased frying pan, then grind them in a mortar. Add the garlic and salt and pound to a fine paste.\\r\\nAdd the paste and the harissa to the soup and simmer until the chickpeas are tender, about 30 minutes.\\r\\nSeason to taste with salt, pepper and lemon juice and serve hot','https:\\/\\/www.themealdb.com\\/images\\/media\\/meals\\/x2fw9e1560460636.jpg','Soup','https:\\/\\/www.youtube.com\\/watch?v=BgRifcCwinY','olive oil','onion','Chickpeas','Vegetable Stock','Cumin','garlic','salt','Harissa Spice','pepper','lime','2 tbs','1 medium finely diced','250g','1.5L','1 tsp','5 cloves','1/2 tsp','1 tsp','pinch','1/2','http:\\/\\/allrecipes.co.uk\\/recipe\\/43419\\/leblebi--tunisian-chickpea-soup-.aspx','https://www.themealdb.com/images/media/meals/x2fw9e1560460636.jpg','null','null')")
    }

    override fun onUpgrade(db: SQLiteDatabase?, oldVersion: Int, newVersion: Int) {

    }

    companion object {
        val readableDatabase: SQLiteDatabase
            get() {
                TODO()
            }
    }

}
